name: Display Name

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  display_name:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Acess
      run: chmod +x display_name.sh
    - name: Run Bash script
      run: ./display_name.sh
